### ISSUE TITLE
Option to add branch protection rules

### ISSUE THREAD

**Issue by santiagoreyerohpe** [HewlettPackard/yoda#13]
It will be interesting to have an option to use the GitHub feature "Branch Restriction". In some cases, you would like to block a list of branches across several repositories base on a patter match

![image](https://user-images.githubusercontent.com/48993629/75859069-a5e96e00-5df9-11ea-8e9f-36116295d700.png)

**Comment by jens-markussen** [comment]
I'm not quite sure I understand what function Yoda would do in this context? Yoda works on GitHub issues.. ?

**Comment by santiagoreyerohpe** [comment]
Nothing related with GitHub issues. This is related with Git Branches. It should be easy... there is an API:
https://developer.github.com/v3/repos/branches/#update-branch-protection
https://developer.github.com/v3/repos/branches/#get-branch-protection
https://developer.github.com/v3/repos/branches/#delete-branch-protection

**Comment by jens-markussen** [comment]
Right. Yoda is primarily focused on GitHub issues (and associated things like labels and milestones). Code-related stuff (including branches) must be the focus of other tools. Closing.
