### ISSUE TITLE
Add wild-card or search support to burndown repository list

### ISSUE THREAD

**Issue by mungojam** [HewlettPackard/yoda#18]
We're making good use of the yoda tools so thanks for sharing it.

Now that we are adding more and more repositories into yoda, it's getting a bit unmanageable. As it happens, all of them have the same name prefix so it would be great if there were a way to pass in a wildcard or some other way of searching for repositories.

I guess it would need to use this API

https://docs.github.com/en/rest/reference/search#search-repositories

**Comment by jens-markussen** [comment]
Hello @mungojam. We have received similar requests from multiple sources.

In HPE, we had a situation with an organization with several hundres of respos representing a number of products. What we ended up doing was to use repository topics (the keywords shown on the right on the front page for GitHub.com repos under "About"). On GitHub Enterprise, it shows up graphically a bit different.

What we did was to apply product topics systematically to the repositories. Also, we applied a topic "issues" to indicate that this repository contains issues. 

Now for dashboards, etc. we may select repositories by putting `repotopic=(comma-sp list of repository topics)`. Eg. `repotopic=CoolProduct1,issues`.

We _could_ also allow `repolist` to include wildcards on repo-names. Would this fit your needs?

**Comment by jens-markussen** [comment]
This is now done. Feedback welcome. What has changed?

1) Ability to search in the repository field (was always there) has been complemented by a "Select all Matches" field at the beginning of the selection field. Choosing this will put all the repositories matching the search as the current repositories. If selected initially (i.e. before starting to type a search) it will simply select _all_ repositories for that organization.

2) Ability to specify a (final) wildcarding for the `repolist` argument. Example: https://hewlettpackard.github.io/yoda/yoda-time-stats.html?owner=HewlettPackard&repolist=yoda*

Enjoy (and comments welcome).

**Comment by mungojam** [comment]
Neat, thanks Jens :). We will be able to use that new wildcard support easily, and the topics one is handy to know about too!

I've just posted a follow up issue #19 which will complete the story for us.

I hope to have enough time to contribute to this project in future as we're making good use of it!
