### ISSUE TITLE
Option to hide top panels

### ISSUE THREAD

**Issue by mungojam** [HewlettPackard/yoda#19]
Following on from #18 which will really help us as we add new repositories to our big list.

The main niggle now is that even if we search with a wildcard in the URL, we still end up with a big list in the text box so the top area takes up a lot of space and we have to scroll down to see the actual chart.

It would be neat if there were a button and url option we could add that would hide/minimise the top panel, a bit like the maximise view in GitHub projects. We generally won't be changing any options within each sprint so the options at the top are redundant for us for 99% of the time.

**Comment by jens-markussen** [comment]
Hi @mungojam. This is in fact already supported. Quoting from the Yoda manual (it may not be too visible...):

> Note: A further URL argument, draw, will result in the graph being drawn immediately (without the user having to press “Draw Chart” button). Simply add “draw=true” to URL. Similarly, it is possible to hide the header (e.g. if including the graph into a dashboard as an iFrame) by putting “hideheader=true”

So, I'm closing this one for now.

However, I am looking at options to restrict the vertical space taken up by the repository selection box, when selecting many repos. Will explore a mechanim by which you will see something like `(x repositories selected)` when x exceeds say 10. Stay tuned.

**Comment by mungojam** [comment]
Amazing, thanks. And apologies, I admit I hadn't even looled for a manual in this case which is unusual for me!

I realize now from this and my other issue that there are some things only supported in the URL so the manual is key for those. That's absolutely cool with us since we will always use bookmarks for these dashboards.

**Comment by jens-markussen** [comment]
Additionally, I've done now a bit extra.

As part of the Yoda menu (the "Hamburger" menu top left), there are now two new entries. One to hide the top panel (except the hamburger) and one to get it back. You can control this as well with URL argument `hidepanel=true`.

The panels for the Burndown and Velocity reports have been slightly reorganized to ensure that the repository selection are in the top panel and - for Velocity report- that the Milestone definition was moved to the second panel.
