### ISSUE TITLE
Create Milestone button no longer working

### ISSUE THREAD

**Issue by Causb1A** [HewlettPackard/yoda#22]
Just noticed when using the tool that the Create Milestone button not working in the new way that you're importing function in the milestone manager. I could be doing something wrong. Not sure. Worth a look.

the function is not defined:
![image](https://user-images.githubusercontent.com/79050900/214838455-b7f203e8-2999-42b5-81b4-65172425ebc9.png)

Tagging
@jens-markussen

**Comment by jens-markussen** [comment]
Will check now @Causb1A

**Comment by jens-markussen** [comment]
Problem confirmed and fixed. Thank for reporting.

**Comment by Causb1A** [comment]
Cheers thanks @jens-markussen
