### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by jayvdb** [HewlettPackard/yoda#3]
It seems yoda was built for a lovely world where issues are always created for every chunk of work to be done.

At least the interface always says Issues and never says Pull Requests, and [code search](https://github.com/HewlettPackard/yoda/search?q=pull+requests&unscoped_q=pull+requests) suggests that PRs are usually filtered out.  If there is a section which handles Pull Requests, it doesnt seem obvious.

Over in the real world .. people do drive-by pull requests without creating an issue first.

It would be nice to be able to switch to Pull Requests for some of the stats views, or a separate view, and  ideally be able to filter out Pull Requests which are linked to Issues (which is not always easy to do).

If a org/repo has a policy of creating an issue for every chunk of work, this PR view would be used by managers as an  exception report to check for any open PRs which dont yet have issues created, and any closed PRs which have fallen through the cracks and wont appear on the other view.

**Comment by jens-markussen** [comment]
Sorry for not responding earlier. Somehow E-mail notifications went to my spam folder. Will consider and respond soon.

**Comment by jens-markussen** [comment]
It is certainly true that Yoda purposely filters out Pull Requests and concerns itself only with "real" issues. Typically, our pull request are "noise" from a stats/tracking perspective, but I can we that it could be usefull - at least for statistical graphs - to enable a selection. Maybe even to the the point of 1) only issues 2) issues AND pull requests, or 3) just pull requests.

**Comment by jens-markussen** [comment]
I'll take this issue to imply ability of time stat report to also be able to consider pull requests (radio selection) and add enhancement labels with priority medium.

**Comment by jens-markussen** [comment]
Thinking that maybe it is time to reopen this discussion. There are however, multiple things to consider, including:

- issue / PR linking. How to represent
- PR's seldom have many labels (even if they could).. This would render graphs rather uninteresting (volume/timing mostly).
