### ISSUE TITLE
expected completion line in burndown chart

### ISSUE THREAD

**Issue by Joshuaalbert** [HewlettPackard/yoda#7]
Hi Yoda team,

Great tool. I was wondering if you could add a simple line that estimates the story points will be zero (keeping xlim pinned to the one imposed by end date of the milestone). This could be default be toggled off, then toggled on when desired. Currently, a simple but time consuming hack is to modify the due date until the ideal line seems to fit the data. This would be useful for conveying visually how far before or after the stipulated end date the milestone could be completed.

Thanks

**Comment by jens-markussen** [comment]
Ok, let me think about that one. Normally sprints tend to be overfilled, but I get the point that this could be helpful to illustrate just how much you are ahead :-)

**Comment by Joshuaalbert** [comment]
Thanks for considering it. I think a simple linear regression line would be useful for over/under-filled sprints, to see how many days the sprint is over/under-shooting. Otherwise, it's of course still possible to do "chi-by-eye".

**Comment by jens-markussen** [comment]
Hi @Joshuaalbert , I've added this feature to burndown. I'm calling it "TrendLine".

Give it a try.

I did not really want to extend automatically the date range if it would be late. Instead (at least for first shot), I've added the Trending end date to the legend.

The trendline is done using linear regression with a first starting point.

**Comment by Joshuaalbert** [comment]
Wow, looks great. I like that you don't extend past the end of the burndown date, and simply add the date of completion in the trendline label. I am having troubles with displaying it on one of my milestones though. It displays properly on two of milestones, but not one one. I can't see what the difference is. How shall I give you debug data? This is an embedded Iframe where you can see it doesn't plot the trend line but if you change the milestone to "Paper 4" or "Paper 2" it works: https://joshuaalbert.github.io/thesis/

**Comment by jens-markussen** [comment]
Hi @Joshuaalbert , it does work for Paper 3 actually. It just so happens that the trendline overlaps with the existing burndown line. You can see this by changing the duedate manually to a few days later..

**Comment by jens-markussen** [comment]
Done.
