### ISSUE TITLE
Burndown doesn't update if you change issue after closing issue

### ISSUE THREAD

**Issue by Joshuaalbert** [HewlettPackard/yoda#8]
Suppose you realise that a label or milestone or estimate or anything about an issue should change after the issue is closed. This could happen if you change this to better reflect reality and if you use past milestones to get better priors for future sprint planning. The burndown does not update until you reopen (and then reclose the issue).

**Comment by jens-markussen** [comment]
Hmm, if you press draw, Yoda should draw based on whatever data is in. You can add l else, change milestones, etc on closed issues if you wish. 

Did I misunderstand?

**Comment by Joshuaalbert** [comment]
What I noticed, and thought was a bug, was that I closed an issue, then changed an estimate in the body of closed issue, then went to redraw chart and it did not change. But when I opened and closed the issue and went to redraw, it drew correctly.

**Comment by jens-markussen** [comment]
Closing/no-issue
